### ISSUE TITLE
[feat] make IntroArtist, Introteam

### ISSUE THREAD

**Issue by YunNa000** [YunNa000/ArtDocentAI_IndustryAcademic#1]
## Background
- 

## Todo
- [x] IntroArtist page 완료
- [x] Introteam pate 완료
- [x] menu tab에 mainpage 추가
